### ISSUE TITLE
'emailto' retrieving userid with a comma

### ISSUE THREAD

**Issue by MotasemHA** [moodleou/moodle-report_customsql#107]
I can't receive the scheduled email. When I extracted the data I noticed that the emailto field has a comma then my userid, I checked the other records but it has nothing like that. 
<img width="590" alt="ad-hoc report" src="https://user-images.githubusercontent.com/98815655/156188457-f7f183f5-1e72-4958-8985-b3bb3bf0bda6.PNG">

I hope you can help,

Regards
Motasem

**Comment by timhunt** [comment]
I think you don;t have the latest version of this plugin installed. There was a bug, but it was fixed in version 4.1 of the plugin. https://github.com/moodleou/moodle-report_customsql/commit/aed200630ce7169b48ee5bd6a949103efc32a546

**Comment by MotasemHA** [comment]
Thanks Tim, 

I really appreciate your help, I checked the version that we have we still have the 4.0 one. 

Regards
Mo
